name: DNS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update DNS Record
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TXT_RECORD: ${{ secrets.TXT_RECORD }}
        run: |
          # Example script to update TXT DNS record
          curl -X POST "https://api.cloudflare.com/client/v4/zones/YOUR_ZONE_ID/dns_records/YOUR_RECORD_ID" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"type":"TXT","name":"YOUR_SUBDOMAIN","content":"${{ secrets.TXT_RECORD }}","ttl":3600,"proxied":false}'
